server:
  port: 8761

spring:
  config:
    activate:
      onProfile: default
  application:
    name: discovery-server

eureka:

  instance:
    hostname: localhost
    preferIpAddress: true
    leaseExpirationDurationInSeconds: 30
    leaseRenewalIntervalInSeconds: 30


  client:
    fetchRegistry: false
    registerWithEureka: false

  datacenter: zdev
  environment: Development


---

server:
  port: 8761


spring:
  config:
    activate:
      onProfile: profile-01
  application:
    name: discovery-server

eureka:

  instance:
    hostname: http://discovery-server-1.zdev.com
    preferIpAddress: true
    leaseExpirationDurationInSeconds: 30
    leaseRenewalIntervalInSeconds: 30


  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://discovery-server-2.mitzdevocode.com:8762/eureka,http://discovery-server-3.zdev.com:8763/eureka

  datacenter: zdev
  environment: Development

---

server:
  port: 8762


spring:
  config:
    activate:
      onProfile: profile-02
  application:
    name: discovery-server

eureka:

  instance:
    hostname: http://discovery-server-2.zdev.com
    preferIpAddress: true
    leaseExpirationDurationInSeconds: 30
    leaseRenewalIntervalInSeconds: 30


  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://discovery-server-1.zdev.com:8761/eureka,http://discovery-server-3.zdev.com:8763/eureka

  datacenter: zdev
  environment: Development

---

server:
  port: 8763


spring:
  config:
    activate:
      onProfile: profile-03
  application:
    name: discovery-server

eureka:

  instance:
    hostname: http://discovery-server-3.mitzdevocode.com
    preferIpAddress: true
    leaseExpirationDurationInSeconds: 30
    leaseRenewalIntervalInSeconds: 30


  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery-server-1.zdev.com:8761/eureka,http://discovery-server-2.zdev.com:8762/eureka

  datacenter: zdev
  environment: Development
